services:
  attack-node-router:
    image: sussybakacute/loadservice-attack-node-router:latest
    env_file:
      - ./attack-node-router/.env
    restart: unless-stopped

  reverse-proxy:
    image: sussybakacute/loadservice-reverse-proxy:latest
    env_file:
      - ./reverse-proxy/.env
    volumes:
      - ./reverse-proxy/config.json:/app/config.json:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
