services:
  postgres:
    image: postgres:16-alpine
    container_name: postgresql-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: sussybaka
      POSTGRES_PASSWORD: sussybakadeptrai
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq-container
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: sussybaka
      RABBITMQ_DEFAULT_PASS: sussybakadeptrai
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql-data:
  redis-data:
  rabbitmq-data:
