services:
  postgres:
    image: postgres:16-alpine
    container_name: postgresql-container
    restart: always
    environment:
      POSTGRES_USER: sussybaka
      POSTGRES_PASSWORD: sussybakadeptrai
      POSTGRES_DB: darksocial
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgresql-data:
