export const RABBITMQ_ATTACK_QUEUE = Symbol('RABBITMQ_ATTACK_QUEUE');
export const RABBITMQ_ATTACK_STATUS_QUEUE = Symbol(
  'RABBITMQ_ATTACK_STATUS_QUEUE',
);
export const RABBITMQ_PAYMENT_QUEUE = Symbol('RABBITMQ_PAYMENT_QUEUE');
